{application,shoehorn,
             [{applications,[kernel,stdlib,elixir,crypto]},
              {description,"Get your boot on."},
              {modules,['Elixir.Shoehorn',
                        'Elixir.Shoehorn.ApplicationController',
                        'Elixir.Shoehorn.Handler',
                        'Elixir.Shoehorn.Handler.Ignore',
                        'Elixir.Shoehorn.Handler.Proxy',
                        'Elixir.Shoehorn.Release','Elixir.Shoehorn.Utils']},
              {registered,[]},
              {vsn,"0.7.0"},
              {mod,{'Elixir.Shoehorn',[]}}]}.
