{application,ring_logger,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"A ring buffer backend for Elixir Logger with IO streaming"},
              {modules,['Elixir.Collectable.RingLogger.CircularBuffer',
                        'Elixir.Enumerable.RingLogger.CircularBuffer',
                        'Elixir.Inspect.RingLogger.CircularBuffer',
                        'Elixir.RingLogger','Elixir.RingLogger.Autoclient',
                        'Elixir.RingLogger.CircularBuffer',
                        'Elixir.RingLogger.Client',
                        'Elixir.RingLogger.Client.State',
                        'Elixir.RingLogger.Server',
                        'Elixir.RingLogger.Server.State']},
              {registered,[]},
              {vsn,"0.8.1"}]}.
